### ISSUE TITLE
Raw search does nothing

### ISSUE THREAD

**Issue by anton-veretenenko** [madmimi/madmimi-php#1]
Search with $raw = true return the same data as with $raw = false. For example, Marc said If I search with raw I can find user even if he is in suppressed list. And this does not work. I just get empty audience tag.
Wiki page http://madmimi.com/developer/Search have no information about Raw parameter.

**Comment by secretfader** [comment]
Looking into this now.

**Comment by secretfader** [comment]
I'll update the wiki page now. I couldn't seem to reproduce this, so I'll be closing this ticket. Get in touch with me directly - send code to nicholas(@)madmimi.com, and let's see what we can work out.
