### ISSUE TITLE
List api returning xml output

### ISSUE THREAD

**Issue by RushabhJoshi** [madmimi/madmimi-php#12]
``` php
$mimi->Lists();
```

returns xml response

though it is a expected behaviour is there a any simple way to directly get array or object?

**Comment by hozyali** [comment]
any solution you found for this?

**Comment by flippakitten** [comment]
You would need to parse the XML into an array.

It might be easier to parse the JSON version which is found at "/audience_lists/lists.json"
You can then simply do a json = json_decode($json).

Something like:

``` php
$json_string = 'https://api.madmimi.com/audience_lists/lists.json/?username=email@email.com&api_key=xxx';
$json_data = file_get_contents($json_string);
$array = json_decode($json_data,true);
foreach ($array as $k=>$v){
    echo $v['name'].'<br />'; // etc.
}
```

You could also update line 127 in the MadMimi.class.php to return json instead:
`$request = $this->DoRequest('/audience_lists/lists.json', $this->default_options(), $return);`
then just do something like

``` php
$json_data = $mimi->Lists();
$array = json_decode($json_data,true);
foreach ($array as $k=>$v){
    echo $v['name'].'<br />'; // etc.
}
```

Haven't tested the second solution but it should work, remember to test

**Comment by hozyali** [comment]
Hi, thanks for your solution. I figured that out already. Here is what I did.

```
$mm_lists = $mailer->Lists();
                    // Parse lists using xml data parser
                    $xml = simplexml_load_string($mm_lists) or die("Error: Cannot create object");
                    foreach ($xml->children() as $mm_child) {
echo 'List ID: '. $mm_child[0]['id'].' => List Name: '. $mm_child[0]['name'];
}
```

I used the above code to generate the list id and name in a drop down select tag. works like a charm. 

Thanks.
