### ISSUE TITLE
Curl error: error:14077458:SSL routines:SSL23_GET_SERVER_HELLO:reason(1112)

### ISSUE THREAD

**Issue by PrimozRome** [madmimi/madmimi-php#5]
I am using this MadMimi PHP library to send promotions using MadMimi API. I was sending without problems but today I was getting this CURL error:

Curl error: error:14077458:SSL routines:SSL23_GET_SERVER_HELLO:reason(1112)
error:14077458:SSL routines:SSL23_GET_SERVER_HELLO:reason(1112).

I googlef for the error I found this: https://bugs.php.net/bug.php?id=61276. The comment suggests this:

The problem has been solved:
When using curl CURLOPT_SSLVERSION must be set to 3
All this works.

I have then added this line into DoRequest fucntion and the CURL error was gone: `curl_setopt($ch, CURLOPT_SSLVERSION, 3);`

I suggest updating the library with this part of code?

```
function DoRequest($path, $options, $return_status = false, $method = 'GET', $mail = false) {
    if ($method == 'GET') {
        $request_options = "?";
    } else {
        $request_options = "";
    }
    $request_options .= http_build_query($options);
    if ($mail == false) {
        $url = "http://api.madmimi.com{$path}";
    } else {
        $url = "https://api.madmimi.com{$path}";
    }
    if ($method == 'GET') {
        $url .= $request_options;
    }
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $url);
    // Fix libcurl vs. apache2
    curl_setopt($ch, CURLOPT_HTTPHEADER, array("Expect:"));
    if ($return_status == true) {
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, false);
    } else {
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    }
    switch($method) {
        case 'GET':
            break;
        case 'POST':
            curl_setopt($ch, CURLOPT_POST, TRUE);
            curl_setopt($ch, CURLOPT_POSTFIELDS, $request_options);
            if (strstr($url, 'https')) {
                curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, FALSE);
                curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, FALSE);
                curl_setopt($ch, CURLOPT_SSLVERSION, 3);
            }
            break;
    }
    if ($this->debug == true) {
        echo "URL: {$url}<br />";
        if ($method == 'POST') {
            echo "Request Options: {$request_options}";
        }
    } else {
        $result = curl_exec($ch);
        if( $result === false){
          $error = curl_error($ch);
        echo 'Curl error: ', $error, "\n";
        die($error);
        }
    }
    curl_close($ch);
    if ($this->debug == false) {
        return $result;
    }
}
```

**Comment by PrimozRome** [comment]
Additionally I just found from MadMimi's stuff that they moved to new servers today ("I just heard that we moved to new servers this morning which is why you were seeing this."). I guess this caused the issue and explains why this was not happening before today...

**Comment by marcheiligers** [comment]
This is related to a bug in OpenSSL (http://stackoverflow.com/questions/8619706/running-curl-with-openssl-0-9-8-against-openssl-1-0-0-server-causes-handshake-er). I'm going to put your fix into the lib. Thanks for checking this out.

**Comment by jbrowning** [comment]
Marking this issue as closed. Please let us know if you run into any more SSL-related issues with our php lib.

**Comment by mancha1** [comment]
You've bumped up against a bug in OpenSSL 0.9.8 in its handling of warning-level alerts. In this case it appears to be hostname mismatch when using SNI extensions.

I've submitted a patch to OpenSSL that addresses this.

--mancha 

[1] https://rt.openssl.org/Ticket/Display.html?id=3038&user=guest&pass=guest
[2] http://marc.info/?t=136760077700002&r=1&w=2
