### ISSUE TITLE
cURL SSL options are set to FALSE which makes SSL requests vulnerable to MITM.

### ISSUE THREAD

**Issue by Ladadadada** [madmimi/madmimi-php#6]
At https://github.com/madmimi/madmimi-php/blob/master/MadMimi.class.php#L79

CURLOPT_SSL_VERIFYPEER should be TRUE
CURLOPT_SSL_VERIFYHOST should be 2.

The correct values are the default values so those lines can be deleted.

Setting these to FALSE causes cURL to not verify the certificate is valid and not verify that the hostname in the certificate matches the hostname in the request.  Either of these options allow active man-in-the-middle attacks.

References:

http://stackoverflow.com/questions/13740933/security-consequences-of-disabling-curlopt-ssl-verifyhost-libcurl-openssl
http://core.trac.wordpress.org/ticket/16904

**Comment by cesutherland** [comment]
Looks like this is all taken care of now!  See:
d4af9cde4af479127a3a62bfec601b3cc6cf31f9
86cb087a689c4b78298bf85b94118805080ae92e
